name: Open SSH session only

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - name: Try tmate session (primary)
        id: tmate
        continue-on-error: true
        timeout-minutes: 5
        uses: mxschmitt/action-tmate@v3

      - name: Fallback to upterm if tmate failed
        if: steps.tmate.outcome != 'success'
        uses: owenthereal/action-upterm@v1
